<div class="about-container">
    <h1>About the SingDict project</h1>
    <p>
        Welcome to our website! SingDict is an open-source dictionary of
        Singlish terms built upon definitions as generated by ChatGPT. It
        includes entries from Wordnet and Wiktionary, and entries contributes by
        native speakers of Singlish. The data is hosted on our <a
            href="https://github.com/singdict/SingDict"
            target="_blank"
            title="Link to SingDict GitHub">GitHub page</a
        > under the CC by SA 4.0 license.
    </p>
    <p>
        Thank you for visiting our About page. We welcome contributions through
        our "Contribute" page!
    </p>
</div>

<svelte:head>
    <title>About SingDict</title>
    <meta name="description" content="about singdict" />
</svelte:head>

<style>
    .about-container {
        max-width: 800px;
        margin: 40px auto 0 auto;
        padding: 20px;
        text-align: center;
    }

    h1 {
        color: #d1d9e0;
        font-size: 2em; /* Adjust the size as needed */
        font-weight: 450; /* Medium font weight */
        margin-bottom: 12px;
    }

    p {
        color: #d1d9e0;
        line-height: 1.6;
        font-size: 1em; /* Standard paragraph size */
        font-weight: 400; /* Normal font weight */
        margin-bottom: 20px; /* Adds space between paragraphs */
    }
    a {
        color: #5cb1dc; /* Bright color for visibility (e.g., Tomato) */
        /* font-weight: bold; Make the link text bold */
        /* text-decoration: underline; Underline the link */
        transition: color 0.3s ease; /* Smooth transition for color change */
    }

    a:hover {
        color: #3b6dcb; /* Slightly darker color on hover (e.g., OrangeRed) */
        text-decoration: underline; /* Ensure underline on hover */
    }
</style>
